version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  php:
    build:
        context: ./php
    volumes:
      - ../wwwroot/:/var/www/
      - ./php/php7.4.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    networks:
      - backend

  nginx:
      build:
        context: ./nginx
      volumes:
        - ../wwwroot/:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
      depends_on:
      - php
      networks:
        - frontend
        - backend

  mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=5.7
      environment:
        - MYSQL_DATABASE=
        - MYSQL_USER=
        - MYSQL_PASSWORD=
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./data/mysql:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        - backend

  redis:
      build: ./redis
      volumes:
        - ./data/redis:/data
      ports:
        - "6379:6379"
      networks:
        - backend